## YAML Template.
---
#Spring properties
spring: 
    application: 
        name: accounts-service
    freemarker:
        enabled: false
        
# Discovery Server Access
eureka:
        client:
                serviceUrl:
                    defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
    port: 2222